# Generated by Django 6.0.4 on 2026-04-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="image",
            field=models.ImageField(default=1, upload_to="uc/"),
            preserve_default=False,
        ),
    ]
