# Generated by Django 6.0.4 on 2026-04-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_unidadecurricular_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ano",
            old_name="numero",
            new_name="ano",
        ),
    ]
