# Generated by Django 6.0.4 on 2026-04-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename_numero_ano_ano"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="pagina_lusofona",
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="image",
            field=models.ImageField(blank=True, upload_to="uc/"),
        ),
    ]
