# Generated by Django 6.0.4 on 2026-04-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_docente_pagina_lusofona_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="categorias",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="data",
        ),
        migrations.RemoveField(
            model_name="makingof",
            name="tipo_registo",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="data",
        ),
        migrations.AddField(
            model_name="makingof",
            name="image",
            field=models.ImageField(default=1, upload_to="registos/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projeto",
            name="image",
            field=models.ImageField(blank=True, upload_to="projetos/"),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="image",
            field=models.ImageField(blank=True, upload_to="tecnologias/"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="github_url",
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
