# Generated by Django 6.0.4 on 2026-04-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_remove_projeto_categorias_remove_makingof_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="ano",
        ),
        migrations.AddField(
            model_name="tfc",
            name="image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chaves",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="pdf",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
