# Generated by Django 6.0.4 on 2026-04-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_remove_tfc_ano_tfc_image_tfc_licenciatura_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
