# Generated by Django 6.0.4 on 2026-04-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_tfc_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makingof",
            name="image",
        ),
        migrations.AddField(
            model_name="makingof",
            name="ficheiro",
            field=models.FileField(default=1, upload_to="registos/"),
            preserve_default=False,
        ),
    ]
