# Generated by Django 6.0.4 on 2026-04-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_remove_makingof_image_makingof_ficheiro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(
                blank=True, related_name="ucs", to="portfolio.docente"
            ),
        ),
    ]
