# Generated by Django 6.0.4 on 2026-04-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_unidadecurricular_docentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="docente",
            name="cardCode",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="docente",
            name="degree",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="docente",
            name="regimen",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
