# Generated by Django 6.0.4 on 2026-04-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_docente_cardcode_docente_degree_docente_regimen"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="ects",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
