# Generated by Django 6.0.4 on 2026-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_unidadecurricular_ects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadecurricular",
            name="ects",
            field=models.IntegerField(blank=True),
        ),
    ]
