# Generated by Django 6.0.4 on 2026-04-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_alter_unidadecurricular_ects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="ects",
        ),
    ]
