# Generated by Django 6.0.4 on 2026-04-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_remove_unidadecurricular_ects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.CharField(max_length=100),
        ),
    ]
