# Generated by Django 6.0.4 on 2026-04-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_unidadecurricular_ects"),
    ]

    operations = [
        migrations.AddField(
            model_name="formacao",
            name="tecnologia",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formacoes",
                to="portfolio.tecnologia",
            ),
            preserve_default=False,
        ),
    ]
