# Generated by Django 6.0.4 on 2026-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_formacao_tecnologia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="ficheiro",
            field=models.FileField(blank=True, upload_to="registos/"),
        ),
    ]
