# Generated by Django 6.0.5 on 2026-05-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0017_alter_makingof_ficheiro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=255),
        ),
    ]
