# Generated by Django 6.0.5 on 2026-05-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0018_alter_tfc_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chaves",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.CharField(max_length=255),
        ),
    ]
