# Generated by Django 6.0.5 on 2026-05-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0019_alter_tfc_palavras_chaves_alter_tfc_tecnologias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="area",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(max_length=255),
        ),
    ]
