# Generated by Django 6.0.5 on 2026-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0020_alter_tfc_area_alter_tfc_autor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="area",
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="palavras_chaves",
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=355),
        ),
    ]
